name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - '**'
    paths-ignore:
     - '.github/workflows/ci.yml'
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.15.4

      - name: Install yarn
      - run: npm install -g yarn

      - name: Install dependences
      - run: yarn install

      - name: Run tests
      - run: yarn copy-db && yarn test:e2e
