services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - node_modules_data:/app/node_modules
    networks:
      - main

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - main

  postgres:
    image: postgres:alpine
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  node_modules_data:
    driver: "local"
  postgres_data:
    driver: "local"
